In [1]:
import yfinance as yf
import pandas as pd
import investpy
import numpy as np
import pandas_datareader.data as web

In [2]:
data = yf.download(  # or pdr.get_data_yahoo(...
        # tickers list or string as well
        tickers = "MTF=F",
        start="2011-01-01",
        end="2021-11-13",
        interval = "3mo",
        group_by = 'ticker',
    )

[*********************100%***********************]  1 of 1 completed

In [4]:
data

                  Open        High         Low       Close   Adj Close  Volume
Date
2010-12-01  132.000000  132.000000  119.000000  120.000000  120.000000      78
2011-03-01  119.750000  129.750000  119.750000  122.150002  122.150002     128
2011-06-01  121.849998  126.349998  120.800003  125.650002  125.650002     193
2011-09-01  126.199997  126.199997  111.099998  112.000000  112.000000     365
2011-12-01  111.949997  112.099998   97.750000   97.750000   97.750000    2135
2012-03-01   97.150002  101.250000   86.500000   88.250000   88.250000    1365
2012-06-01   88.250000   95.400002   86.099998   93.800003   93.800003     735
2012-09-01   92.500000   92.500000   86.349998   89.500000   89.500000    4185
2012-12-01   92.099998   92.099998   86.199997   87.660004   87.660004    2395
2013-03-01   88.199997   88.199997   78.250000   82.050003   82.050003    5870
2013-06-01   77.650002   77.650002   73.800003   75.699997   75.699997    2855
2014-03-01   73.150002   77.400002   73.150002   74.849998   74.849998    7934
2014-09-01   76.150002   76.150002   71.199997   74.150002   74.150002    5665
2014-12-01   72.150002   72.150002   57.900002   61.900002   61.900002    8080
2015-06-01   57.500000   58.750000   55.750000   55.869999   55.869999    4663
2015-09-01   55.250000   55.250000   51.650002   53.779999   53.779999    5185
2015-12-01   48.900002   48.900002   43.400002   43.880001   43.880001    5230
2016-03-01   44.750000   48.250000   44.049999   48.150002   48.150002    4701
2016-06-01   48.150002   61.650002   48.150002   60.230000   60.230000    4055
2016-09-01   61.750000   89.550003   60.000000   85.900002   85.900002    6080
2016-12-01   85.150002   90.750000   79.349998   82.260002   82.260002    3570
2017-03-01   78.900002   78.900002   72.650002   74.529999   74.529999    1623
2017-06-01   77.250000   87.800003   77.250000   87.800003   87.800003    3145
2017-09-01   88.099998   95.250000   88.099998   92.750000   92.750000    2267
2017-12-01   92.699997   96.400002   81.550003   81.550003   81.550003    1817
2018-03-01   79.349998   95.000000   53.450001   95.000000   95.000000    1455
2018-06-01   95.349998  102.400002   63.599998   97.650002   97.650002    1917
2018-09-01   97.639999  101.250000   66.250000   88.500000   88.500000     998
2018-12-01   88.489998   88.849998   73.300003   75.000000   75.000000    1731
2019-03-01   74.699997   75.250000   54.150002   56.450001   56.450001    1697
2019-06-01   56.450001   58.849998   48.700001   54.250000   54.250000    1817
2020-06-01   38.580002   51.200001   38.580002   49.029999   49.029999     922
2020-09-01   49.029999   57.750000   49.029999   53.790001   53.790001     475
2020-12-01   53.790001   70.750000   53.790001   65.900002   65.900002     859
2021-03-01   65.500000   86.099998   65.099998   86.099998   86.099998     533
2021-06-01   95.900002  154.600006   95.900002  154.600006  154.600006    1932
2021-09-01  157.899994  274.000000  138.750000  139.500000  139.500000    2316